name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest
    env:
      CI: true
      working-directory: .\docker\mssqlssis
      IMAGE_NAME: mssqlssis
      IMAGE_ID: ${{secrets.OPENSHIFT_REGISTRY}}/5b7aa5-tools/mssqlssis

    steps:
    - uses: actions/checkout@v2
    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@v1
      with:

      # "mirror" is the default source, so this is optional.
        source: "mirror"

      # Installs the latest kam release.
        kam: "latest"

      # Installs the latest release of oc with the major version 3.
      # This is equivalent to "3.x" or "^3".
        oc: "3"

      # Installs the latest release of odo with the major version 2, and the minor version 0.
      # This would install odo 2.0.3, but not odo 2.1.0.
        odo: "2.0"

      # This exact version will install version 0.11.0 of Tekton, no other version.
        tkn: "0.11.0"
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      env:
          OPENSHIFT_USER: ${{secrets.OC_USERNAME_SA}}
          OPENSHIFT_NAMESPACE: 5b7aa5-tools
          SERVER_URL: ${{secrets.OPENSHIFT_SERVER}}
          OPENSHIFT_REGISTRY: ${{secrets.OPENSHIFT_REGISTRY}} 

      with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
    
    - name: Login to OpenShift Container Registry
      uses: docker/login-action@v1
      with:
          registry: ${{secrets.OPENSHIFT_REGISTRY}}
          username: ${{ secrets.OC_USERNAME_SA }}
          password: ${{ secrets.OPENSHIFT_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
          context: .\docker\mssqlssis
          push: true
          tags:  ${{secrets.OPENSHIFT_REGISTRY}}/5b7aa5-tools/mssqlssis:latest

